### ISSUE TITLE
[config] Quiet leave?

### ISSUE THREAD

**Issue by xshotD** [moustacheminer/MSS-Autobanr#2]
Some people would prefer not being DMed about their guild being banned or the bot owner may not like DMing people for this.

**Comment by lepon01** [comment]
I believe that people who make these bot collection servers should be ridiculed for what they are doing:

1. They waste CPU time of servers, where some are single core 512MB Raspberry Pis or DigitalOcean instances
2. They slow down the experience for legitimate users
3. This is a semi-automatic process; they only receive the message if:
    - They purposefully add the bot to a bot collection server, which is bad
    - They set up automated process to scan legitimate bot enthusiasts servers
    I believe it is the fault of the end user of attempting to make these collection servers and automatically adding them

Overall, I strongly believe the people who owns bot collection servers should be notified of what they are doing, and how it is wrong.

I understand that a bot owner may NOT want to notify people, for instance:

1. By notifying the person, they will be notified that the bot has left, and therefore can re-add the bot
2. There may be so many automated bot collection servers, that it may max out the rate limit of the Discord API

Overall, I will implement this feature in the future, but it will be enabled as default, with a heavy warning (like the one above) about the disadvantages of disabling it.

Thanks!

**Comment by lepon01** [comment]
This has been added in the latest commit.

**Comment by xshotD** [comment]
:ok_hand:

**Comment by lepon01** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by xshotD** [comment]
:eyes:
